### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by elmerbulthuis** [hammerjs/hammer.js#1062]
`npm run build` show this:

```
resolve failed:  { Error: Cannot find module 'serve'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/elmerbulthuis/workspace/hammer.js/node_modules/require-relative/index.js:30:17)
    at resolve (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/elmerbulthuis/workspace/hammer.js/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } serve
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (/home/elmerbulthuis/workspace/hammer.js/node_modules/require-relative/index.js:30:17)
    at resolve (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/home/elmerbulthuis/workspace/hammer.js/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/home/elmerbulthuis/workspace/hammer.js/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' } babel-runtime
```

The `serve` and `babel-runtime` dependencies seem to be missing!

see also #1061

**Comment by askot** [comment]
I needed to build a custom release and had the same issue. However, building from 2.0.8 works (https://github.com/hammerjs/hammer.js/commit/49731688380a91be07653ee2491ab48ece7952b5), it looks like building setup was updated and something broke.

**Comment by galfert** [comment]
I also encountered this problem. Updating the dev dependency `babel-preset-es2015-rollup` to the most recent version (3.0.0) fixed it.
